services:

  crawler:
    build: ./crawler/
    volumes:
      - ./data/crawler:/data/crawler
      - ./data/mentions:/data/mentions
      - ./data/coreference:/data/coreference
      - ./data/dblp-export:/data/dblp-export
      - ./data/gesis-export:/data/gesis-export

  mentions:
    build: ./mentions/
    volumes:
      - ./data/crawler:/data/crawler
      - ./data/mentions:/data/mentions
      - ./data/coreference:/data/coreference
      - ./data/dblp-export:/data/dblp-export
      - ./data/gesis-export:/data/gesis-export
    depends_on:
      crawler:
        condition: service_completed_successfully

  coreference:
    build: ./coreference/
    volumes:
      - ./data/crawler:/data/crawler
      - ./data/mentions:/data/mentions
      - ./data/coreference:/data/coreference
      - ./data/dblp-export:/data/dblp-export
      - ./data/gesis-export:/data/gesis-export
    depends_on:
      mentions:
        condition: service_completed_successfully

  dblp-export:
    build: ./dblp-export/
    volumes:
      - ./data/crawler:/data/crawler
      - ./data/mentions:/data/mentions
      - ./data/coreference:/data/coreference
      - ./data/dblp-export:/data/dblp-export
      - ./data/gesis-export:/data/gesis-export
    depends_on:
      coreference:
        condition: service_completed_successfully

  gesis-export:
    build: ./gesis-export/
    volumes:
      - ./data/crawler:/data/crawler
      - ./data/mentions:/data/mentions
      - ./data/coreference:/data/coreference
      - ./data/dblp-export:/data/dblp-export
      - ./data/gesis-export:/data/gesis-export
    depends_on:
      coreference:
        condition: service_completed_successfully
