services:

  crawler:
    build: ./crawler/
    volumes:
      - ./output/crawler:/output/crawler
      - ./output/mentions:/output/mentions
      - ./output/coreference:/output/coreference
      - ./output/dblp-export:/output/dblp-export

  mentions:
    build: ./mentions/
    volumes:
      - ./output/crawler:/output/crawler
      - ./output/mentions:/output/mentions
      - ./output/coreference:/output/coreference
      - ./output/dblp-export:/output/dblp-export
    depends_on:
      crawler:
        condition: service_completed_successfully

  coreference:
    build: ./coreference/
    volumes:
      - ./output/crawler:/output/crawler
      - ./output/mentions:/output/mentions
      - ./output/coreference:/output/coreference
      - ./output/dblp-export:/output/dblp-export
    depends_on:
      mentions:
        condition: service_completed_successfully

  dblp-export:
    build: ./dblp-export/
    volumes:
      - ./output/crawler:/output/crawler
      - ./output/mentions:/output/mentions
      - ./output/coreference:/output/coreference
      - ./output/dblp-export:/output/dblp-export
    depends_on:
      coreference:
        condition: service_completed_successfully
