services:
  crawler:
    build: ./crawler/
    volumes:
      - ./data/crawler:/data/crawler
      - ./data/mentions:/data/mentions
      - ./data/coreference:/data/coreference
      - ./data/dblp-export:/data/dblp-export
      - ./data/gesis-export:/data/gesis-export

  grobid-service:
    image: grobid/grobid:0.8.0
    restart: "unless-stopped"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://grobid-service:8070/api/isalive"]
      interval: 30s
      timeout: 10s
      retries: 5

  mentions:
    build: ./mentions
    volumes:
      - ./data/mentions:/app/src/resources/data
    depends_on:
      grobid-service:
        condition: service_healthy

  coreference:
    build: ./coreference/
    volumes:
      - ./data/crawler:/data/crawler
      - ./data/mentions:/data/mentions
      - ./data/coreference:/data/coreference
      - ./data/dblp-export:/data/dblp-export
      - ./data/gesis-export:/data/gesis-export
    depends_on:
      mentions:
        condition: service_completed_successfully

  dblp-export:
    build: ./dblp-export/
    volumes:
      - ./data/crawler:/data/crawler
      - ./data/mentions:/data/mentions
      - ./data/coreference:/data/coreference
      - ./data/dblp-export:/data/dblp-export
      - ./data/gesis-export:/data/gesis-export
    depends_on:
      coreference:
        condition: service_completed_successfully

  gesis-export:
    build: ./gesis-export/
    volumes:
      - ./data/crawler:/data/crawler
      - ./data/mentions:/data/mentions
      - ./data/coreference:/data/coreference
      - ./data/dblp-export:/data/dblp-export
      - ./data/gesis-export:/data/gesis-export
    depends_on:
      coreference:
        condition: service_completed_successfully
