warc_dir: "/data/crawler/test_job/latest/warcs/" #note that "latest" is symbolic link
output_dir: "/data/mentions/web-mentions/"
model_checkpoint: "Yousef-Cot/dataset-mention-extractor"  # f"src/resources/models/fold{exp}"
question: "On which data the study is based?"
# 4 "Which data samples or images are used"
# 3 "On which data the study is based"
# 2 "Which dataset or database is used?"
# 1 "Is there any use of data collected from a survey"
# 0 "What data are used?" #
short_context_length: 5
strict_threshold: 5



