pdf_dir: "./src/resources/data/in_pdfs"
tei_dir: "/data/mentions/out_tei/"  #"./src/resources/data/out_tei"
grobid_config: "./config.json" #
extraction_dir: "/data/mentions/results" #./src/resources/data/results"
results_in_json: "/data/mentions/pdfs_extraction.json"
model_checkpoint: "./resources/models/best_model/fold{exp}"
strict_threshold: 5
short_context_length: 10
grobid_batch_size: 1 #number of pdfs to handle per batch


